apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: vertx-webapp
  name: vertx-webapp
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
      nodePort: 30101
  selector:
    io.kompose.service: vertx-webapp


