apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: bercelik/producer_vertx_app:v1.0
          ports:
            - containerPort: 8085
          env:
            - name: USER_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: USER_PWD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres-service
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app.kubernetes.io/name: webapp
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085