apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: consumer-app
  name: consumer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: consumer-app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: consumer-app
    spec:
      containers:
        - image: bercelik/consumer_app:v1.0
          name: consumer_app
          resources: {}
      restartPolicy: Always
status: {}
